// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOR6UneRGFpaFOpO6ZlkBldq-VgnGUzvk',
    appId: '1:814470913920:web:720f8669ce5eaa712c6b65',
    messagingSenderId: '814470913920',
    projectId: 'livenotes-49113',
    authDomain: 'livenotes-49113.firebaseapp.com',
    storageBucket: 'livenotes-49113.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpEbxJ1FSoHA8nXOt6Ufwnhmx9YCXz0NE',
    appId: '1:814470913920:android:ba1e456890f86e182c6b65',
    messagingSenderId: '814470913920',
    projectId: 'livenotes-49113',
    storageBucket: 'livenotes-49113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP1A-Kwr4hMUg5rKoNu0ZyH2mK1guDxrY',
    appId: '1:814470913920:ios:26accce1bfd01d222c6b65',
    messagingSenderId: '814470913920',
    projectId: 'livenotes-49113',
    storageBucket: 'livenotes-49113.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP1A-Kwr4hMUg5rKoNu0ZyH2mK1guDxrY',
    appId: '1:814470913920:ios:26accce1bfd01d222c6b65',
    messagingSenderId: '814470913920',
    projectId: 'livenotes-49113',
    storageBucket: 'livenotes-49113.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOR6UneRGFpaFOpO6ZlkBldq-VgnGUzvk',
    appId: '1:814470913920:web:547227f4a812b6ec2c6b65',
    messagingSenderId: '814470913920',
    projectId: 'livenotes-49113',
    authDomain: 'livenotes-49113.firebaseapp.com',
    storageBucket: 'livenotes-49113.firebasestorage.app',
  );
}
